service: sls-api # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
plugins:
  - serverless-offline
functions:
  hello:
    handler: handler.hello
  jobs:
    handler: src/jobs/handler.handler
  listJobs:
    handler: src/jobs/list.handler
    events:
      - http:
          method: GET
          path: /jobs
  createJob:
    handler: src/jobs/create.handler
    events:
      - http:
          method: POST
          path: /jobs

